// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/notifications/GroupedTimeline.tsx": () => import("../components/mockups/notifications/GroupedTimeline.tsx"),
  "./components/mockups/notifications/SocialFeed.tsx": () => import("../components/mockups/notifications/SocialFeed.tsx")
};
